# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://limistah.dev"
title: Aleem Isiaka
theme: [PaperMod]
pagination:
  pagerSize: 15

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: true
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "books", "journals"]

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
      papers: papers
    menu:
      main:
        - name: About
          url: about/
          weight: 99
        - name: Search
          url: search/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Readings
          url: readings/
          weight: 3
        - name: Links
          url: links/
          weight: 4 

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: English

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Aleem Isiaka and his intersection with Software Engineering, DevOps, Cloud and CloudNative Tools, Articifial Intelligence, and the Microprocessors powering them."
  author: ["Aleem Isiaka"]
  comments: true
  defaultTheme: PaperMod
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  TocOpen: true
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: limistah
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: 🤗 Welcome Home!
    Content: >
      - Here, I _hack_ the internals of **Software Engineering/Architecture**, **Cloud/DevOps**, **Microprocessors**, and **Artificial Intelligence**. I remove the magic from technologies by showing how they work from the inside, reflecting my appreciation of how these technologies have evolved from an idea in a few minds to become part of our everyday lives. Read more about me [here](/about/).

      - <br/>

      - Please support by following me on [GitHub](https://github.com/limistah) and [X/Twitter](https://twitter.com/limistah). Do so share with your friends on social media.

  socialIcons:
    - name: X
      title: Follow me on X/Twitter
      url: "https://x.com/intent/tweet/?text=Checkout%20This%20Post%20By%20limistah%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/limistah/limistah.dev"
    - name: github
      title: Follow me on Github
      url: "https://github.com/limistah"
    - name: linkedin
      title: Reach me on LinkedIn
      url: "https://linkedin.com/in/limistah"
    - name: stackoverflow
      title: Stackoverflow Profile
      url: https://stackoverflow.com/users/7368018/limistah
    - name: email
      title: Let's Talk!
      url: mailto:aleemisiaka@gmail.com
    - name: cv
      title: Support my family...
      url: /aleemisiaka.pdf
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/limistah"

  editPost:
    URL: "https://github.com/limistah/limistah.dev/tree/main/content"
    Text: "Fix and Improve this content" # edit text
    appendFilePath: true # to append file path to Edit link


  assets:
    disableHLJS: true
    favicon: "/assets/avatar.png"


markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
  googleAnalytics:
    ID: "G-0TT6LT81J0"
