# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://limistah.dev"
title: Aleem (limistah)'s Crib
theme: [PaperMod]
pagination:
  pagerSize: 10

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: About
          url: about/
          weight: 5
        - name: Blog
          url: posts/
          weight: 5
        - name: Links
          url: links/
          weight: 8
        - name: Search
          url: search/
          weight: 10

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: English

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Reimagining software engineering, trends, best practices and principles"
  author: ["Aleem Isiaka"]
  comments: true
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: limistah
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Aleem Isiaka - AI's Crib"
    Content: >
      - 👋 Welcome to limistah's crib!

      - Here, I attempt to **reImagine engineering** and share information on how to become the better of our best versions.

      - Feel free to show your support by following me on [GitHub](https://github.com/limistah) and [X/Twitter](https://twitter.com/limistah). You can also share with your friends on social media.
      
      - Read more about me [here](/about/)

  socialIcons:
    - name: X
      title: Share On on X/Twitter
      url: "https://x.com/intent/tweet/?text=Checkout%20This%20Post%20By%20limistah%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/limistah/limistah.dev"
    - name: github
      title: View Source on Github
      url: "https://github.com/limistah"
    - name: linkedin
      title: Reach me on LinkedIn
      url: "https://linkedin.com/in/limistah"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/limistah"
    - name: email
      title: email
      url: mailto:aleemisiaka@gmail.com
    - name: cv
      title: CV
      url: /aleemisiaka.pdf

  editPost:
    URL: "https://github.com/limistah/limistah.dev/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link


  assets:
    disableHLJS: true
    favicon: "/assets/avatar.png"


markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
  googleAnalytics:
    ID: "G-0TT6LT81J0"
