name: Vouch Check Issue

on:
  issues:
    types: [opened, reopened]

permissions:
  contents: read
  issues: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: mitchellh/vouch/action/check-issue@c6d80ead49839655b61b422700b7a3bc9d0804a9 # v1
        with:
          issue-number: ${{ github.event.issue.number }}
          auto-close: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
